### ISSUE TITLE
Je veux en tant qu'ADMIN SUPPRIMER les COMMENTAIRES indésirables

### ISSUE THREAD

**Issue by alexCampus** [campus-digital-grenoble/blog-Kepajualan#7]

**Comment by kevinRznd** [comment]
is not closed

**Comment by GRR-GRR** [comment]
http://stackoverflow.com/questions/39878465/laravel-vue-js-authentication

**Comment by GRR-GRR** [comment]
https://laracasts.com/discuss/channels/general-discussion/hide-button-if-user-is-logged-with-laravel-and-vuejs
